setting default indent and improving cctest output

diff --git a/zshrc_v8 b/zshrc_v8
--- a/zshrc_v8
+++ b/zshrc_v8
@@ -125,7 +125,8 @@ ninja_d8() {
                 #clean the < from --list output
                 TEST=${TEST%"<"}
                 cd $ROOT && \
-                show_cmd $BUILD/cctest $TEST
+                    ( show_cmd $BUILD/cctest $TEST || echo "${RED}FAILED 💀$NO_COLOR" )
+
             done
         fi
 
